// CHEFS
export const GET_ALL_CHEFS = "GET_ALL_CHEFS";
export const CREATE_CHEF = "CREATE_CHEF";
export const SELECT_CHEF = "SELECT_CHEF";
export const DESELECT_CHEF = "DESELECT_CHEF";
export const PATCH_CHEF = "PATCH_CHEF";
export const DELETE_CHEF = "DELETE_CHEF";
export const CHEF_ERROR = "CHEF_ERROR";
export const SET_LOADING = "SET_LOADING";

// Ingredients
export const GET_ALL_INGREDIENTS = "GET_ALL_INGREDIENTS";
export const INGREDIENTS_LOADING = "INGREDIENTS_LOADING";
export const INGREDIENT_ERROR = "INGREDIENT_ERROR";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";
export const SELECT_INGREDIENT = "SELECT_INGREDIENT";
export const PATCH_INGREDIENT = "PATCH_INGREDIENT";
export const DESELECT_INGREDIENT = "DESELECT_INGREDIENT";
