// CHEFS
export const GET_ALL_CHEFS = "GET_ALL_CHEFS";
export const CREATE_CHEF = "CREATE_CHEF";
export const SELECT_CHEF = "SELECT_CHEF";
export const DESELECT_CHEF = "DESELECT_CHEF";
export const PATCH_CHEF = "PATCH_CHEF";
export const DELETE_CHEF = "DELETE_CHEF";
export const CHEF_ERROR = "CHEF_ERROR";
export const SET_LOADING = "SET_LOADING";

// Ingredients
export const GET_ALL_INGREDIENTS = "GET_ALL_INGREDIENTS";
export const INGREDIENTS_LOADING = "INGREDIENTS_LOADING";
export const INGREDIENT_ERROR = "INGREDIENT_ERROR";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";
export const SELECT_INGREDIENT = "SELECT_INGREDIENT";
export const PATCH_INGREDIENT = "PATCH_INGREDIENT";
export const DESELECT_INGREDIENT = "DESELECT_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";

// Recipes
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const RECIPE_LOADING = "RECIPE_LOADING";
export const RECIPE_ERROR = "RECIPE_ERROR";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const SELECT_RECIPE = "SELECT_RECIPE";
export const PATCH_RECIPE = "PATCH_RECIPE";
export const DESELECT_RECIPE = "DESELECT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";


